version: "3.8"

x-timezone: &timezone
  Asia/Tokyo

services:
  go:
    platform: linux/x86_64
    image: golang:1.17.5
    environment:
      TZ: *timezone
    working_dir: /var/www/src
    volumes:
      - type: bind
        source: ../src
        target: /var/www/src
    depends_on:
      - db

  nginx:
    platform: linux/x86_64
    image: nginx:1.21.4
    environment:
      TZ: *timezone
    ports:
      - 8881:80
      - 4444:443
    volumes:
      - type: bind
        target: /var/www/src
        source: ../src
      - type: bind
        target: /etc/conf.d
        source: ./docker/nginx/conf
      - type: bind
        target: /etc/ssl
        source: ./docker/nginx/ssl

  db:
    platform: linux/x86_64
    image: mysql:8.0
    environment:
      TZ: *timezone
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: go_app
    ports:
      - 3301:3306
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
